apiVersion: v1
kind: Service
metadata:
  name: ims-frontend
  labels:
    app: ims
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: ims
    tier: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
